export const TAB_NAME = {
  candidateOverview: "candidateOverview",
  position: "position",
  application: "application",
  scheduled: "scheduled",
  trainingOverview: "trainingOverview",
  project: "project",
  task: "task",
  trainingResult: "trainingResult",
};

export const DRAWER_TAB_NAME = {
  profileStack: "profileStack",
  recruitmentProcess: "recruitmentProcess",
  candidateTraining: "candidateTraining",
  settingStack: "settingStack",
  changePassword: "changePassword",
};

export const SCREEN_NAME = {
  profileScreen: "profileScreen",
  profileEditingScreen: "profileEditingScreen",
  signInScreen: "signInScreen",
  jobScreen: "jobScreen",
  jobDetailScreen: "jobDetailScreen",
  jobCreationScreen: "jobCreationScreen",
  jobEditingScreen: "jobEditingScreen",
  jobCandidateCreationScreen: "jobCandidateCreationScreen",
  candidateScreen: "candidateScreen",
  candidateDetailScreen: "candidateDetailScreen",
  candidateEditingInfoScreen: "candidateEditingInfoScreen",
  candidateCreationScreen: "candidateCreationScreen",
  candidateOverviewScreen: "candidateOverviewScreen",
  scheduleScreen: "scheduleScreen",
  scheduleListScreen: "scheduleListScreen",
  scheduleDetailScreen: "scheduleDetailScreen",
  scheduleAddition: "scheduleAddition",
  scheduleDetailEditingScreen: "scheduleDetailEditingScreen",
  projectScreen: "projectScreen",
  taskScreen: "taskScreen",
  projectDetailScreen: "projectDetailScreen",
  taskDetailScreen: "taskDetailScreen",
  projectCreationScreen: "projectCreationScreen",
  projectEditingScreen: "projectEditingScreen",
  projectMemberEditingScreen: "projectMemberEditingScreen",
  projectTaskEditingScreen: "projectTaskEditingScreen",
  projectTaskCreationScreen: "projectTaskCreationScreen",
  taskCreationScreen: "taskCreationScreen",
  taskEditingScreen: "taskEditingScreen",
  settingScreen: "settingScreen",
  settingTagScreen: "settingTagScreen",
  settingUsersScreen: "settingUsersScreen",
  settingUserCreationScreen: "settingUserCreationScreen",
  projectOverviewScreen: "projectOverviewScreen",
  trainingResultScreen: "trainingResultScreen",
  trainingResultDetailScreen: "trainingResultDetailScreen",
  trainingResultEditingScreen: "trainingResultEditingScreen",
  trainingResultCreationScreen: "trainingResultCreationScreen",
};
